<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title><?= $title ?? 'PHP Apprentice' ?></title>
    <meta name="description" content="<?= $subtitle ?? 'A site for learning how to use PHP' ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="/css/site.css">
    <link rel="icon" href="/favicon-32.png">
    <script src="/js/site.js"></script>
</head>

<body>
