<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title><?= $title ?? 'PHP Apprentice' ?></title>
    <meta name="description" content="<?= $subtitle ?? 'A site for learning how to use PHP' ?>">

    <link rel="stylesheet" href="<?php echo asset('css/site.css') ?>">
    <link rel="icon" href="/favicon-32.png">
    <script src="<?php echo asset('js/site.js') ?>"></script>
</head>

<body>
