<div class="table-of-contents">
    <h4>Table of Contents</h4>
    <a href="<?= page_path('index') ?>">Preface</a>
    <ol>
        <li><a href="<?= page_path('basics') ?>">Basics</a></li>
        <li><a href="<?= page_path('variables') ?>">Variables</a></li>
        <li><a href="<?= page_path('arithmetic') ?>">Arithmetic</a></li>
        <li><a href="<?= page_path('comparisons') ?>">Comparisons</a></li>
        <li><a href="<?= page_path('boolean-logic') ?>">Boolean Logic</a></li>
        <li><a href="<?= page_path('conditionals') ?>">Conditionals</a></li>
        <li><a href="<?= page_path('loops') ?>">Loops</a></li>
        <li><a href="<?= page_path('arrays') ?>">Arrays</a></li>
        <li><a href="<?= page_path('functions') ?>">Functions</a></li>
        <li><a href="<?= page_path('classes') ?>">Classes</a></li>
    </ol>
    <a href="<?= page_path('credits') ?>">Credits</a>
</div>
