<div class="table-of-contents">
    <h4>Table of Contents</h4>
    <ul class="list-plain">
        <li><a href="/">Preface</a></li>
        <li><a href="<?= page_path('installing-php') ?>">Installing PHP</a></li>
    </ul>

    <h5 class="section-title">Basics</h5>
    <ol>
        <li><a href="<?= page_path('basics') ?>">Basics</a></li>
        <li><a href="<?= page_path('variables') ?>">Variables</a></li>
        <li><a href="<?= page_path('arithmetic') ?>">Arithmetic</a></li>
        <li><a href="<?= page_path('strings') ?>">Strings</a></li>
        <li><a href="<?= page_path('comparisons') ?>">Comparisons</a></li>
        <li><a href="<?= page_path('boolean-logic') ?>">Boolean Logic</a></li>
        <li><a href="<?= page_path('conditionals') ?>">Conditionals</a></li>
        <li><a href="<?= page_path('loops') ?>">Loops</a></li>
        <li><a href="<?= page_path('arrays') ?>">Arrays</a></li>
        <li><a href="<?= page_path('functions') ?>">Functions</a></li>
        <li><a href="<?= page_path('classes') ?>">Classes</a></li>
        <li><a href="<?= page_path('classes-inheritance') ?>">Classes: Inheritance</a></li>
        <li><a href="<?= page_path('classes-visibility') ?>">Classes: Visibility</a></li>
        <li><a href="<?= page_path('classes-constructor') ?>">Classes: Constructor</a></li>
        <li><a href="<?= page_path('static') ?>">Static</a></li>
        <li><a href="<?= page_path('interfaces') ?>">Interfaces</a></li>
        <li><a href="<?= page_path('abstract') ?>">Abstract Classes</a></li>
        <li><a href="<?= page_path('exceptions') ?>">Exceptions</a></li>
    </ol>

    <h5 class="section-title">Web</h5>
    <ol>
        <li><a href="<?= page_path('web/http') ?>">HTTP</a></li>
        <li><a href="<?= page_path('web/http-post') ?>">HTTP POST</a></li>
        <li><a href="<?= page_path('web/http-server') ?>">PHP HTTP Server</a></li>
    </ol>

    <a href="<?= page_path('credits') ?>">Credits</a>
</div>
