<?php partial('header', ['title' => 'PHP Apprentice - Credits']) ?>

<div class="container center">
    <div class="grid-toc">
        <div>
            <h1>Credits</h1>
            <p>
                PHP Apprentice was inspired by
                <a href="https://gobyexample.com/">Go By Example</a> and by <a href="https://elixirschool.com/">Elixir School</a>. Both sites offer excellent, quality documentation in Go and Elixir and I want PHP Apprentice to provide the same
                experience for the PHP programming language.
            </p>
        </div>
        <div>
            <?php partial('table_of_contents') ?>
        </div>
    </div>
</div>

<?php partial('footer') ?>
