<?php partial('header', ['title' => 'PHP Apprentice - Credits']) ?>

<div class="container small center">
    <div class="menu">
        <button class="menu-button" title="Open Menu">
            <div class="icon"><?= icon('menu') ?></div>
            Menu
        </button>
    </div>

    <div>
        <h1>Credits</h1>
        <p>
            PHP Apprentice was inspired by
            <a href="https://gobyexample.com/">Go By Example</a> and by <a href="https://elixirschool.com/">Elixir School</a>. Both sites offer excellent, quality documentation in Go and Elixir and I want PHP Apprentice to provide the same
            experience for the PHP programming language.
        </p>
        <p>
            Sites used as a reference while writing PHP Apprentice:
            <ul>
                <li><a href="https://secure.php.net/" target="_blank">php.net</a></li>
                <li><a href="https://www.phptherightway.com/" target="_blank">PHP The Right Way</a></li>
            </ul>
        </p>
        <p>
            PHP Apprentice was built using several open source projects, besides PHP itself.
            Thank you to each of these maintainers for providing great libraries!
            <ul>
                <li><a href="https://prismjs.com/" target="_blank">Prism.js</a></li>
                <li><a href="https://www.zondicons.com/" target="_blank">Zondicons by Steve Schoger</a></li>
                <li><a href="https://postcss.org/" target="_blank">PostCSS</a></li>
                <li><a href="https://symfony.com/doc/current/components/console.html" target="_blank">Symfony CLI</a></li>
                <li><a href="https://symfony.com/doc/current/frontend.html" target="_blank">Symfony Encore</a></li>
            </ul>
        </p>
        <hr />
        <p>
            phpapprentice.com was created and is managed by <a href="https://twitter.com/restoreddev">Andrew Davis</a>.
        </p>
    </div>
</div>

<div class="modal closed">
    <div class="modal-content">
        <button class="modal-button right" title="Close">
            <div class="icon"><?= icon('close-outline') ?></div>
        </button>
        <?php partial('table_of_contents') ?>
    </div>
</div>

<?php partial('footer') ?>
