<?php partial('header', ['title' => $title, 'subtitle' => $subtitle]) ?>

<div class="container small center">
    <?php partial('menu_button') ?>

    <h1><?= escape($title) ?></h1>
    <h3 class="subtitle"><?= escape($subtitle) ?></h3>
    <?= $chapter ?>

    <div class="clearfix"></div>
    <div class="navigate-links">
        <?php if (!empty($previous)): ?>
            <a href="<?= page_path($previous) ?>" title="Previous">
                <div class="icon"><?= icon('cheveron-outline-left') ?></div>
                Previous
            </a>
        <?php endif ?>
        <?php if (!empty($next)): ?>
            <a href="<?= page_path($next) ?>" title="Next">
                Next
                <div class="icon"><?= icon('cheveron-outline-right') ?></div>
            </a>
        <?php endif ?>
    </div>
</div>


<?php partial('menu_modal') ?>
<?php partial('footer') ?>
